package com.procurement.service;
import com.procurement.dto.AuthDtos.*; import com.procurement.entity.*; import com.procurement.repository.*; import com.procurement.security.JwtService; import org.springframework.beans.factory.annotation.Value; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.security.SecureRandom; import java.util.concurrent.ConcurrentHashMap;
@Service public class AuthService {
 private final UserRepository users; private final FarmerRepository farmers; private final JwtService jwt; private final boolean devOtp; private final ConcurrentHashMap<String,Otp> otps=new ConcurrentHashMap<>(); private final SecureRandom random=new SecureRandom();
 private record Otp(String code,long expiresAt){}
 public AuthService(UserRepository users,FarmerRepository farmers,JwtService jwt,@Value("${app.otp.dev-mode:true}") boolean devOtp){this.users=users;this.farmers=farmers;this.jwt=jwt;this.devOtp=devOtp;}
 @Transactional public AuthResponse register(RegisterRequest r){if(users.findByPhoneNumber(r.phoneNumber()).isPresent())throw new IllegalArgumentException("Phone number already registered"); User u=new User();u.setPhoneNumber(r.phoneNumber());u.setRole(Role.FARMER);u.setActive(true);users.save(u); Farmer f=new Farmer();f.setUser(u);f.setFullName(r.fullName());f.setVillage(r.village());f.setDistrict(r.district());f.setState(r.state());f.setPincode(r.pincode());f.setAlternatePhone(r.alternatePhone());farmers.save(f); return token(u,f);}
 public AuthResponse login(LoginRequest r){User u=users.findByPhoneNumber(r.phoneNumber()).orElseThrow(()->new IllegalArgumentException("User not found; register first"));if(!u.isActive())throw new IllegalArgumentException("Account is inactive"); Farmer f=farmers.findByUserId(u.getId()).orElse(null);return token(u,f);}
 public String sendOtp(OtpRequest r){String code=String.format("%06d",random.nextInt(1_000_000));otps.put(r.phoneNumber(),new Otp(code,System.currentTimeMillis()+300000));return devOtp?code:"OTP sent";}
 public AuthResponse verifyOtp(VerifyOtpRequest r){Otp o=otps.get(r.phoneNumber());if(o==null||o.expiresAt()<System.currentTimeMillis()||!o.code().equals(r.otp()))throw new IllegalArgumentException("Invalid or expired OTP");otps.remove(r.phoneNumber());User u=users.findByPhoneNumber(r.phoneNumber()).orElseThrow(()->new IllegalArgumentException("Register first"));if(!u.isActive())throw new IllegalArgumentException("Account is inactive");return token(u,farmers.findByUserId(u.getId()).orElse(null));}
 private AuthResponse token(User u,Farmer f){String name=f==null?null:f.getFullName();return new AuthResponse(jwt.generate(u.getId(),u.getPhoneNumber(),u.getRole().name()),u.getId(),f==null?null:f.getId(),u.getRole().name(),name);}
}
